### ISSUE TITLE
Pluscal not highlighted

### ISSUE THREAD

**Issue by garrensmith** [wysiib/language-tla-pluscal#3]
This addon is so awesome. It works great for tla+ but it doesn't seem to support writing pluscal. See the image below, the pluscal isn't syntax highted
![Screenshot 2019-05-05 14 23 58](https://user-images.githubusercontent.com/179458/57193991-9b441b00-6f41-11e9-83d0-0ac4acdfc08f.png)

Would you be able to add syntax highlighting for pluscal?

**Comment by wysiib** [comment]
Of course it should work for pluscal. Just to be sure, how would you have expected the example to be highlighted?

**Comment by garrensmith** [comment]
I was hoping that the pluscal in the comments section would be syntax highlighted as well. I'm writing in pluscal and then getting it translated into tla+.

**Comment by wysiib** [comment]
Noted. In addition: should pluscal simply use the same highlighting rules tla+ itself uses?

**Comment by garrensmith** [comment]
Yes. The same would be ideal. Thanks for this library. Using atom for tla+ is awesome

**Comment by wysiib** [comment]
Okay, I'll have to figure out why it does not recognize the special comment including pluscal and thinks it is a regular comment. Will look into it in the coming days!

**Comment by wysiib** [comment]
I just released an updated version including preliminary support for PlusCal comments. Please check it out and report any further issues you find.

**Comment by garrensmith** [comment]
Works great. Thank you
